import type { Metadata } from "next";
import HeaderW from "@/components/header/HeaderW";
import HeaderM from "@/components/header/HeaderM";
import FooterW from "@/components/footer/FooterW";
import FooterM from "@/components/footer/FooterM";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <HeaderW />
          <HeaderM />
        </nav>

        <main>
          {children}
        </main>

        <footer>
          <FooterW />
          <FooterM />
        </footer>
      </body>
    </html>
  );
}
